const express = require('express');
const router = express.Router();
const pool = require('../config/db');
const { requireLogin } = require('../middleware/auth');
const associateModel = require('../models/associate');
const tree = require('../models/tree');
const dash = require('../models/dashboard');

router.use(requireLogin);

// Make current associate + company name available to every view
router.use(async (req, res, next) => {
  res.locals.currentAssociate = await associateModel.findById(req.session.associateId);
  res.locals.companyName = process.env.COMPANY_NAME || 'Company Hub';
  res.locals.activePage = '';
  next();
});

router.get('/dashboard', async (req, res) => {
  const data = await dash.getDashboardData(req.session.associateId);
  res.render('dashboard', { title: 'Dashboard', activePage: 'dashboard', data });
});

// CUSTOMER DETAILS (bookings made by this associate)
router.get('/customers', async (req, res) => {
  const { rows } = await pool.query(
    'SELECT * FROM bookings WHERE associate_id = $1 ORDER BY booking_date DESC',
    [req.session.associateId]
  );
  res.render('customers', { title: 'Customer Details', activePage: 'customers', bookings: rows });
});

// MONTHLY BUSINESS (self + team, broken down by month)
router.get('/monthly-business', async (req, res) => {
  const team = await tree.getAllDescendants(req.session.associateId);
  const teamIds = team.map((t) => t.id);
  teamIds.push(req.session.associateId);

  const { rows } = await pool.query(`
    SELECT to_char(booking_date, 'YYYY-MM') AS month,
           SUM(CASE WHEN associate_id = $1 THEN sqft ELSE 0 END) AS self_sqft,
           SUM(CASE WHEN associate_id = $1 THEN amount ELSE 0 END) AS self_amount,
           SUM(CASE WHEN associate_id <> $1 THEN sqft ELSE 0 END) AS team_sqft,
           SUM(CASE WHEN associate_id <> $1 THEN amount ELSE 0 END) AS team_amount
    FROM bookings
    WHERE associate_id = ANY($2) AND status <> 'cancelled'
    GROUP BY month ORDER BY month DESC LIMIT 12
  `, [req.session.associateId, teamIds]);

  res.render('monthly_business', { title: 'Monthly Business', activePage: 'monthly', rows: rows });
});

// PAYOUT DETAIL (own commissions earned)
router.get('/payout-detail', async (req, res) => {
  const { rows } = await pool.query(`
    SELECT p.*, b.customer_name, b.project_name, b.plot_no
    FROM payouts p JOIN bookings b ON p.booking_id = b.id
    WHERE p.associate_id = $1 ORDER BY p.created_at DESC
  `, [req.session.associateId]);
  res.render('payout_detail', { title: 'Payout Detail', activePage: 'payout', payouts: rows });
});

// TEAM PAYOUT REPORT (commission generated by each team member, per level)
router.get('/team-payout', async (req, res) => {
  const { rows } = await pool.query(`
    SELECT p.*, a.name AS source_name, a.email AS source_email
    FROM payouts p JOIN associates a ON p.source_associate_id = a.id
    WHERE p.associate_id = $1 AND p.level > 0
    ORDER BY p.created_at DESC
  `, [req.session.associateId]);
  res.render('team_payout', { title: 'Team Payout Report', activePage: 'team_payout', payouts: rows });
});

// PAYMENTS (money actually received)
router.get('/payments', async (req, res) => {
  const { rows } = await pool.query(
    'SELECT * FROM payments WHERE associate_id = $1 ORDER BY payment_date DESC',
    [req.session.associateId]
  );
  res.render('payments', { title: 'Payments', activePage: 'payments', payments: rows });
});

// PLOT STATUS
router.get('/plots', async (req, res) => {
  const { rows } = await pool.query('SELECT * FROM plots ORDER BY project_name, plot_no');
  res.render('plots', { title: 'Plot Status', activePage: 'plots', plots: rows });
});

// REFERRAL TREE (full nested downline)
router.get('/referral-tree', async (req, res) => {
  const treeData = await tree.getTreeStructure(req.session.associateId);
  res.render('referral_tree', { title: 'Referral Tree', activePage: 'tree', treeData });
});

// DOWNLINE (flat list of entire team)
router.get('/downline', async (req, res) => {
  const rows = await tree.getAllDescendants(req.session.associateId);
  res.render('downline', { title: 'Downline', activePage: 'downline', rows });
});

// REFERRAL WORK (get your own signup link to share, list direct referrals)
router.get('/referral-work', async (req, res) => {
  const directs = await tree.getDirects(req.session.associateId);
  res.render('referral_work', { title: 'Referral Work', activePage: 'referral_work', directs });
});

// PROFILE EDIT
router.get('/profile', (req, res) => {
  res.render('profile', { title: 'Profile Edit', activePage: 'profile', error: null, success: null });
});

router.post('/profile', async (req, res) => {
  const { name, phone, city, profile_note } = req.body;
  try {
    await associateModel.updateProfile(req.session.associateId, { name, phone, city, profile_note });
    res.locals.currentAssociate = await associateModel.findById(req.session.associateId);
    res.render('profile', { title: 'Profile Edit', activePage: 'profile', error: null, success: 'Profile updated.' });
  } catch (err) {
    console.error(err);
    res.render('profile', { title: 'Profile Edit', activePage: 'profile', error: 'Could not update profile.', success: null });
  }
});

// WELCOME (static info page)
router.get('/welcome', (req, res) => {
  res.render('welcome', { title: 'Welcome', activePage: 'welcome' });
});

// CHANGE PASSWORD
router.get('/change-password', (req, res) => {
  res.render('change_password', { title: 'Change Password', activePage: 'password', error: null, success: null });
});

router.post('/change-password', async (req, res) => {
  const { current_password, new_password, confirm_password } = req.body;
  try {
    const associate = await associateModel.findById(req.session.associateId);
    const ok = await associateModel.verifyPassword(current_password, associate.password_hash);
    if (!ok) {
      return res.render('change_password', { title: 'Change Password', activePage: 'password', error: 'Current password is incorrect.', success: null });
    }
    if (new_password !== confirm_password || new_password.length < 6) {
      return res.render('change_password', { title: 'Change Password', activePage: 'password', error: 'New passwords must match and be at least 6 characters.', success: null });
    }
    await associateModel.changePassword(req.session.associateId, new_password);
    res.render('change_password', { title: 'Change Password', activePage: 'password', error: null, success: 'Password changed successfully.' });
  } catch (err) {
    console.error(err);
    res.render('change_password', { title: 'Change Password', activePage: 'password', error: 'Something went wrong.', success: null });
  }
});

module.exports = router;
